robocin/ssl-core

- protocols/protocols/navigation/navigation.proto
Updates field type on protocols.Navigation proto.
Solves #18
> Use common robot id

- communication-ms/communication-jaiminho/communication/controller/CMakeLists.txt
- communication-ms/communication-jaiminho/communication/controller/consumer_controller.cpp
- communication-ms/communication-jaiminho/communication/controller/consumer_controller.h
- communication-ms/communication-jaiminho/communication/controller/icontroller.cpp
- communication-ms/communication-jaiminho/communication/controller/icontroller.h
- communication-ms/communication-jaiminho/communication/controller/producer_controller.cpp
- communication-ms/communication-jaiminho/communication/controller/producer_controller.h
This pull request add controller classes to communication service.
> Add controller classes to communication

- communication-ms/communication-jaiminho/communication/processing/CMakeLists.txt
- communication-ms/communication-jaiminho/communication/processing/communication_processor.cpp
- communication-ms/communication-jaiminho/communication/processing/communication_processor.h
- communication-ms/communication-jaiminho/communication/processing/robot_command/CMakeLists.txt
- communication-ms/communication-jaiminho/communication/processing/robot_command/robot_command_mapper.cpp
- communication-ms/communication-jaiminho/communication/processing/robot_command/robot_command_mapper.h
This pull request add processing classes to communication service.
> Add processing classes to communication

- communication-ms/communication-jaiminho/communication/parameters/CMakeLists.txt
- communication-ms/communication-jaiminho/communication/parameters/parameters.cpp
- communication-ms/communication-jaiminho/communication/parameters/parameters.h
This pull request add parameters class to communication service.
> Add parameters class to communication

- behavior-ms/behavior-zidane/.devcontainer/devcontainer.json
- behavior-ms/behavior-zidane/CMakeLists.txt
- behavior-ms/behavior-zidane/behavior-zidane.Dockerfile
- behavior-ms/behavior-zidane/behavior-zidane.code-workspace
- behavior-ms/behavior-zidane/behavior/CMakeLists.txt
- behavior-ms/behavior-zidane/behavior/behavior_main.cpp
- docker-compose.dev.yaml
Adds C++ devcontainer for zidane behavior microsservice.
> Add behavior-zidane devcontainer

- common/cpp/robocin/geometry/point2d.h
Add geometry.Point2D methods for navigation and decision calculations.
> Add Geometry.Point2D methods

- common/cpp/robocin/network/CMakeLists.txt
- common/cpp/robocin/network/udp_multicast_socket_sender.cpp
- common/cpp/robocin/network/udp_multicast_socket_sender.h
Esse PR adiciona um sender udp multicast para comunicação com os robos.
> Add sender udp multicast

- docker-compose.lab.yaml
Add services do docker compose `.lab` file.
- communication-ms
- decision-ms
- navigation-ms
- behavior-ms
> Add new microservices .lab compose

- communication-ms/communication-jaiminho/communication/messaging/receiver/payload_mapper.cpp
- navigation-ms/navigation-luffy/navigation/messaging/receiver/payload_mapper.cpp
> Fix remove ilogs

- docker-compose.lab.yaml
This PR fix double key definition in compose.lab
> Fix .lab compose

- decision-ms/decision-guardiola/decision/decision_main.cpp
- decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
- decision-ms/decision-guardiola/decision/processing/decision_processor.h
This PR integrates the classes from the strategy pipeline (coach, tactical plan and evaluators) with the current pipeline of decision (main and processor).
> Integration of strategy pipeline on decision

- decision-ms/decision-guardiola/decision/processing/coach/CMakeLists.txt
- decision-ms/decision-guardiola/decision/processing/coach/coach.cpp
- decision-ms/decision-guardiola/decision/processing/coach/coach.h
This PR adds the Coach class, an implementation of the ICoach interface.
> Add Coach class

- behavior-ms/behavior-bruxo/behavior/behavior_main.cpp
- behavior-ms/behavior-bruxo/behavior/messaging/receiver/message_receiver.cpp
- behavior-ms/behavior-bruxo/behavior/messaging/receiver/message_receiver.h
- behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload.cpp
- behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload.h
- behavior-ms/behavior-bruxo/behavior/messaging/receiver/payload_mapper.cpp
- behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.cpp
- behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.h
> Add referee service subscription

- decision-ms/decision-guardiola/decision/processing/coach/role_manager/role_manager.cpp
- decision-ms/decision-guardiola/decision/processing/coach/role_manager/role_manager.h
This class is responsible to enable decision to choose robot roles.
> [decision-ms] Add role manager

- decision-ms/decision-guardiola/decision/processing/coach/coach.cpp
- decision-ms/decision-guardiola/decision/processing/coach/coach.h
- decision-ms/decision-guardiola/decision/processing/coach/icoach.h
- decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
- decision-ms/decision-guardiola/decision/processing/evaluators/example_evaluator.cpp
- decision-ms/decision-guardiola/decision/processing/evaluators/example_evaluator.h
- decision-ms/decision-guardiola/decision/processing/evaluators/ievaluator.h
Integration of the World as a parameter of the `process` function from `IEvaluator` interface now that the World entity is ready to use.
> Add World as a parameter from the IEvaluator interface

- decision-ms/decision-guardiola/decision/parameters/parameters.h
- decision-ms/decision-guardiola/decision/processing/CMakeLists.txt
- decision-ms/decision-guardiola/decision/processing/analyzer/CMakeLists.txt
- decision-ms/decision-guardiola/decision/processing/analyzer/field_analyzer.cpp
- decision-ms/decision-guardiola/decision/processing/analyzer/field_analyzer.h
- decision-ms/decision-guardiola/decision/processing/coach/CMakeLists.txt
- decision-ms/decision-guardiola/decision/processing/decision_processor.cpp
- decision-ms/decision-guardiola/decision/processing/messages/CMakeLists.txt
- decision-ms/decision-guardiola/decision/processing/messages/perception/field/field_message.h
This PR adds the methods to calculate the points from the field as well as methods to analyzer regions of it.
> Add methods for Field class

- behavior-ms/behavior-bruxo/behavior/parameters/parameters.h
- behavior-ms/behavior-bruxo/behavior/processing/behavior_processor.cpp
- behavior-ms/behavior-bruxo/behavior/processing/entities/world.cpp
- behavior-ms/behavior-bruxo/behavior/processing/entities/world.h
- behavior-ms/behavior-bruxo/behavior/processing/messages/decision/decision_message.cpp
- behavior-ms/behavior-bruxo/behavior/processing/messages/perception/field/field_message.h
This PR adds field message in the behavior world to use in processing
> Add field in behavior world

- behavior-ms/behavior-bruxo/behavior/processing/CMakeLists.txt
- behavior-ms/behavior-bruxo/behavior/processing/analyzer/CMakeLists.txt
- behavior-ms/behavior-bruxo/behavior/processing/analyzer/ball_analyzer.cpp
- behavior-ms/behavior-bruxo/behavior/processing/analyzer/ball_analyzer.h
- behavior-ms/behavior-bruxo/behavior/processing/analyzer/field_analyzer.cpp
- behavior-ms/behavior-bruxo/behavior/processing/analyzer/field_analyzer.h
This PR adds helper functions used throughout the code to derive ball and field information.
> Feat behavior analyzers

- navigation-ms/navigation-luffy/navigation/processing/entities/CMakeLists.txt
- navigation-ms/navigation-luffy/navigation/processing/entities/world.cpp
- navigation-ms/navigation-luffy/navigation/processing/entities/world.h
- navigation-ms/navigation-luffy/navigation/processing/messages/common/peripheral_actuation/peripheral_actuation.cpp
- navigation-ms/navigation-luffy/navigation/processing/messages/common/peripheral_actuation/peripheral_actuation.h
- navigation-ms/navigation-luffy/navigation/processing/messages/common/robot_dribbler/robot_dribbler_message.h
- navigation-ms/navigation-luffy/navigation/processing/messages/planning/planning_message.cpp
- navigation-ms/navigation-luffy/navigation/processing/motion_parser/motion_parser.cpp
- navigation-ms/navigation-luffy/navigation/processing/motion_parser/motion_parser.h
- navigation-ms/navigation-luffy/navigation/processing/navigation_processor.cpp
- navigation-ms/navigation-luffy/navigation/processing/navigation_processor.h
The world entity groups the data from perception, game_status and behavior to use in the Navigation Processor
> [navigation-ms] Add World entity

- behavior-ms/behavior-bruxo/behavior/processing/messages/common/peripheral_actuation/peripheral_actuation.cpp
- behavior-ms/behavior-bruxo/behavior/processing/messages/common/peripheral_actuation/peripheral_actuation.h
- behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_kick/kick_command.cpp
- behavior-ms/behavior-bruxo/behavior/processing/messages/common/robot_kick/kick_command.h
- behavior-ms/behavior-bruxo/behavior/processing/messages/motion/motion_message.cpp
- behavior-ms/behavior-bruxo/behavior/processing/messages/motion/motion_message.h
Add peripheral actuation message to Motion with kick command.
> Add peripheral actuation to motion

- docker-compose.cbr.yaml
Adiciona um novo docker compose utilizado durante a CBR 2024.
> [behavior-ms] Add CBR compose

- behavior-ms/behavior-bruxo/behavior/processing/state_machine/CMakeLists.txt
Add mising dependency on `messages` for `state_machine` lib.
> [behavior-ms] Fix state machine CMakeLists

- communication-ms/communication-jaiminho/communication/messaging/receiver/payload_mapper.cpp
- communication-ms/communication-jaiminho/communication/processing/communication_processor.cpp
- protocols/protocols/communication/communication.proto
Uses navigation outputs to populate communication output message sent to the robot.
> [communication-ms] Populate communication message
